steps:
  copy:
    operations:
      - type: copy
        src: ../animations/vector_animate_web
        dest: .
        hash_check: true
        ignore:
          - "*.md"
          - "example"
          - "node_modules"
          - "test"

  publish:
    version_from: ../animations/vector_animate_web/package.json
    only_if_changes: true
    operations:
      - type: commit
        message: "chore: publish web app {{version}}"
      - type: create_tag
        tag: "vector_animate_web-v{{version}}"
        message: "Web runtime v{{version}}"
      - type: push
        remote: origin
        branch: main
      - type: push_tags
        remote: origin
